import { VettingRequest } from "./types";

export const MOCK_VETTINGS: VettingRequest[] = [
  {
    id: "1",
    subject_name: "John Smith",
    subject_type: "individual",
    company_affiliation: "Smith Enterprises LLC",
    country: "United States",
    city: "Washington, DC",
    brief_bio: "US-based business executive and political consultant with ties to several lobbying firms.",
    referral_source: "Direct referral from Sen. Thompson's office",
    engagement_type: "domestic_political",
    vetting_level: "standard_vet",
    requested_by: "Jim",
    requested_at: "2026-03-05T14:30:00Z",
    status: "completed",
    pipeline_progress: {
      step_0_intake: "completed", step_1_sanctions: "completed", step_2_debarment: "completed",
      step_3_news: "completed", step_4_litigation: "completed", step_5_corporate: "completed",
      step_6_fec: "completed", step_7_sec: "completed", step_8_lobbying: "completed", step_9_synthesis: "completed",
    },
    result_json: {
      subject: { name: "John Smith", type: "individual", company: "Smith Enterprises LLC", country: "US", city: "Washington, DC" },
      gates: {
        sanctions: { status: "PASS", sources_checked: ["OFAC SDN", "UN Sanctions", "EU Sanctions", "OpenSanctions", "Interpol"], matches: [], checked_at: "2026-03-05T14:31:00Z" },
        debarment: { status: "PASS", sources_checked: ["SAM.gov Exclusions", "HHS OIG LEIE"], matches: [], checked_at: "2026-03-05T14:31:05Z" },
      },
      dimensions: {
        litigation_legal: { score: 3.5, weight: 0.22, confidence: "HIGH", summary: "2 resolved civil cases, no criminal record.", sub_factors: { criminal_cases: { score: 0, detail: "No criminal cases found" }, civil_fraud_corruption: { score: 0, detail: "No fraud or corruption cases" }, repeated_civil_litigation: { score: 4, detail: "2 civil suits in past 5 years, both resolved" }, past_resolved: { score: 3, detail: "Smith v. Jones (2022), settled" }, bankruptcy: { score: 0, detail: "No bankruptcy filings" } }, evidence: [{ text: "Smith was defendant in breach of contract suit, settled 2022", source: "CourtListener", url: "https://courtlistener.com/case/12345", date: "2022-06-15", temporal_weight: 0.7 }] },
        media_reputation: { score: 2.0, weight: 0.20, confidence: "HIGH", summary: "Limited media coverage, no major controversies.", sub_factors: {}, evidence: [] },
        international_pep: { score: 0.5, weight: 0.15, confidence: "HIGH", summary: "US-based, not a PEP, no international risk factors.", sub_factors: { pep_status: { score: 0, detail: "Not a Politically Exposed Person" }, country_risk: { score: 1, detail: "US-based, low country risk" } }, evidence: [] },
        financial_sec: { score: 1.0, weight: 0.12, confidence: "HIGH", summary: "No SEC enforcement actions. Clean filing history.", sub_factors: {}, evidence: [] },
        corporate_business: { score: 2.5, weight: 0.11, confidence: "MEDIUM", summary: "3 active companies, ownership structure mostly clear.", sub_factors: {}, evidence: [] },
        political_lobbying: { score: 1.5, weight: 0.10, confidence: "HIGH", summary: "Standard political contributions, no lobbying red flags.", sub_factors: { pay_to_play: { score: 3, detail: "Some contributions to officials with regulatory oversight" } }, evidence: [] },
        conflict_of_interest: { score: 0, weight: 0.10, confidence: "HIGH", summary: "No conflicts with current TMG clients.", sub_factors: { direct_conflict: { score: 0, detail: "No direct conflicts" }, indirect_conflict: { score: 0, detail: "No indirect conflicts" } }, evidence: [] },
      },
      scoring: { raw_composite: 1.73, engagement_multiplier: 1.0, adjusted_composite: 1.73, confidence_modifier: "none", final_composite: 1.73, risk_tier: "LOW", recommendation: "Approve" },
      flags: { red: [], yellow: [{ category: "litigation", title: "Repeated civil litigation", description: "2 civil lawsuits in past 5 years", source: "CourtListener", date: "2022-2024", severity: "minor" }] },
      executive_summary: "## Summary\n\nJohn Smith is a US-based business executive with a clean sanctions and regulatory record. He runs Smith Enterprises LLC out of Washington, DC.\n\n## Key Findings\n\n- **Legal**: Two resolved civil suits, both settled. No criminal record.\n- **Media**: Limited media presence, no negative coverage.\n- **Financial**: Clean SEC and corporate filing history.\n- **Political**: Standard political contributions within normal ranges.\n\n## Recommendation\n\n**APPROVE** — Low overall risk. The two resolved civil suits are minor and well within normal parameters for a political consultant of his tenure.",
      metadata: { pipeline_version: "v1.0", vetting_level: "standard_vet", steps_completed: ["intake", "sanctions", "debarment", "news", "litigation", "corporate", "fec", "sec", "lobbying", "synthesis"], started_at: "2026-03-05T14:30:00Z", completed_at: "2026-03-05T14:42:30Z", total_duration_seconds: 750 },
    },
    composite_score: 1.73,
    risk_tier: "LOW",
    recommendation: "Approve",
    confidence: "HIGH",
    decision: "approved",
    decided_by: "Ben",
    decided_at: "2026-03-05T16:00:00Z",
    decision_notes: "Clean record, low risk. Approved for engagement.",
    completed_at: "2026-03-05T14:42:30Z",
    flags: { red: [], yellow: [{ category: "litigation", title: "Repeated civil litigation", description: "2 civil lawsuits in past 5 years", source: "CourtListener", date: "2022-2024", severity: "minor" }] },
  },
  {
    id: "2",
    subject_name: "Meridian Capital Group",
    subject_type: "organization",
    company_affiliation: null,
    country: "United Arab Emirates",
    city: "Dubai",
    brief_bio: "Dubai-based investment firm seeking US political advisory services for infrastructure projects.",
    referral_source: "Ambassador Collins",
    engagement_type: "fara_foreign_political",
    vetting_level: "deep_dive",
    requested_by: "Tara",
    requested_at: "2026-03-06T09:00:00Z",
    status: "running",
    pipeline_progress: {
      step_0_intake: "completed", step_1_sanctions: "completed", step_2_debarment: "completed",
      step_3_news: "completed", step_4_litigation: "running", step_5_corporate: "pending",
      step_6_fec: "pending", step_7_sec: "pending", step_8_lobbying: "pending",
      step_9_international: "pending", step_10_pep: "pending", step_11_synthesis: "pending",
    },
    result_json: null,
    composite_score: null,
    risk_tier: null,
    recommendation: null,
    confidence: null,
    decision: null,
    decided_by: null,
    decided_at: null,
    decision_notes: null,
    completed_at: null,
    flags: null,
  },
  {
    id: "3",
    subject_name: "Elena Vasquez",
    subject_type: "individual",
    company_affiliation: "Vasquez & Partners Law Firm",
    country: "Mexico",
    city: "Mexico City",
    brief_bio: "Prominent attorney and political advisor seeking partnership on cross-border policy issues.",
    referral_source: "Industry conference contact",
    engagement_type: "foreign_corporate",
    vetting_level: "standard_vet",
    requested_by: "Ben",
    requested_at: "2026-03-06T11:30:00Z",
    status: "completed",
    pipeline_progress: null,
    result_json: {
      subject: { name: "Elena Vasquez", type: "individual", company: "Vasquez & Partners", country: "MX", city: "Mexico City" },
      gates: {
        sanctions: { status: "PASS", sources_checked: ["OFAC SDN", "UN Sanctions", "EU Sanctions", "OpenSanctions", "Interpol"], matches: [], checked_at: "2026-03-06T11:31:00Z" },
        debarment: { status: "PASS", sources_checked: ["SAM.gov Exclusions", "HHS OIG LEIE"], matches: [], checked_at: "2026-03-06T11:31:05Z" },
      },
      dimensions: {
        litigation_legal: { score: 1.0, weight: 0.22, confidence: "HIGH", summary: "No litigation found in US databases.", sub_factors: {}, evidence: [] },
        media_reputation: { score: 4.5, weight: 0.20, confidence: "MEDIUM", summary: "Mixed media coverage. 3 articles linking to controversial political figure.", sub_factors: {}, evidence: [{ text: "Vasquez mentioned in connection with former governor under investigation", source: "Reuters", url: "https://reuters.com/article/123", date: "2025-11-20", temporal_weight: 1.0 }] },
        international_pep: { score: 5.0, weight: 0.15, confidence: "MEDIUM", summary: "Close associate of PEP. Country risk: Moderate.", sub_factors: { pep_status: { score: 6, detail: "Close associate of former governor (PEP)" }, country_risk: { score: 4, detail: "Mexico — moderate country risk" } }, evidence: [] },
        financial_sec: { score: 0, weight: 0.12, confidence: "HIGH", summary: "No US financial exposure.", sub_factors: {}, evidence: [] },
        corporate_business: { score: 2.0, weight: 0.11, confidence: "LOW", summary: "Limited public info on firm. Spanish-language sources only.", sub_factors: {}, evidence: [] },
        political_lobbying: { score: 0, weight: 0.10, confidence: "HIGH", summary: "No US lobbying activity.", sub_factors: {}, evidence: [] },
        conflict_of_interest: { score: 0, weight: 0.10, confidence: "HIGH", summary: "No conflicts identified.", sub_factors: {}, evidence: [] },
      },
      scoring: { raw_composite: 2.17, engagement_multiplier: 1.15, adjusted_composite: 2.50, confidence_modifier: "medium_penalty", final_composite: 3.25, risk_tier: "MODERATE", recommendation: "Conditional Approve" },
      flags: { red: [{ category: "pep", title: "PEP association", description: "Close associate of former governor under federal investigation", source: "Reuters/OpenSanctions", date: "2025", severity: "major" }], yellow: [{ category: "media", title: "Controversial media coverage", description: "3 articles linking to politically sensitive figures", source: "Reuters", date: "2025", severity: "moderate" }, { category: "confidence", title: "Low confidence on corporate data", description: "Limited English-language sources for corporate background", source: "Pipeline", date: "2026", severity: "minor" }] },
      executive_summary: "## Summary\n\nElena Vasquez is a Mexico City-based attorney and political advisor. While she has no direct sanctions or legal issues, her close association with a former governor currently under federal investigation raises concerns.\n\n## Key Findings\n\n- **PEP Association**: Close associate of former Jalisco governor under federal investigation\n- **Media**: Mixed coverage, 3 articles connecting her to controversial political figure\n- **Corporate**: Limited English-language corporate data available\n\n## Recommendation\n\n**CONDITIONAL APPROVE** — Moderate risk. Recommend additional due diligence on PEP association and engagement-specific FARA analysis before proceeding.",
      metadata: { pipeline_version: "v1.0", vetting_level: "standard_vet", steps_completed: ["intake", "sanctions", "debarment", "news", "litigation", "corporate", "fec", "sec", "lobbying", "synthesis"], started_at: "2026-03-06T11:30:00Z", completed_at: "2026-03-06T11:45:00Z", total_duration_seconds: 900 },
    },
    composite_score: 3.25,
    risk_tier: "MODERATE",
    recommendation: "Conditional Approve",
    confidence: "MEDIUM",
    decision: null,
    decided_by: null,
    decided_at: null,
    decision_notes: null,
    completed_at: "2026-03-06T11:45:00Z",
    flags: { red: [{ category: "pep", title: "PEP association", description: "Close associate of former governor under federal investigation", source: "Reuters/OpenSanctions", date: "2025", severity: "major" }], yellow: [{ category: "media", title: "Controversial media coverage", description: "3 articles linking to politically sensitive figures", source: "Reuters", date: "2025", severity: "moderate" }] },
  },
  {
    id: "4",
    subject_name: "Viktor Petrov",
    subject_type: "individual",
    company_affiliation: "Petrov Holdings AG",
    country: "Russia",
    city: "Moscow",
    brief_bio: "Russian oligarch seeking US government relations support for energy sector interests.",
    referral_source: "Unknown — cold outreach via website",
    engagement_type: "fara_foreign_political",
    vetting_level: "deep_dive",
    requested_by: "Shannon",
    requested_at: "2026-03-04T08:00:00Z",
    status: "gates_failed",
    pipeline_progress: { step_0_intake: "completed", step_1_sanctions: "failed" },
    result_json: {
      subject: { name: "Viktor Petrov", type: "individual", company: "Petrov Holdings AG", country: "RU", city: "Moscow" },
      gates: {
        sanctions: { status: "FAIL", sources_checked: ["OFAC SDN", "UN Sanctions", "EU Sanctions", "OpenSanctions", "Interpol"], matches: [{ list: "OFAC SDN", matched_name: "Viktor A. Petrov", confidence: 97, details: "Listed under Executive Order 14024, Russia-related sanctions" }, { list: "EU Sanctions", matched_name: "Viktor Petrov", confidence: 94, details: "EU Council Regulation 269/2014" }], checked_at: "2026-03-04T08:01:00Z" },
        debarment: { status: "PASS", sources_checked: ["SAM.gov Exclusions", "HHS OIG LEIE"], matches: [], checked_at: "2026-03-04T08:01:05Z" },
      },
      dimensions: {} as any,
      scoring: { raw_composite: 10, engagement_multiplier: 1.3, adjusted_composite: 10, confidence_modifier: "none", final_composite: 10, risk_tier: "CRITICAL", recommendation: "Auto-Reject" },
      flags: { red: [{ category: "sanctions", title: "OFAC SDN Match", description: "97% match on OFAC Specially Designated Nationals list", source: "OFAC", date: "2026-03-04", severity: "critical" }], yellow: [] },
      executive_summary: "## AUTO-REJECTED\n\nViktor Petrov matched against OFAC SDN list with 97% confidence. Subject is sanctioned under Executive Order 14024 (Russia-related). No further vetting was conducted. **Legal counsel must be consulted before any engagement.**",
      metadata: { pipeline_version: "v1.0", vetting_level: "deep_dive", steps_completed: ["intake", "sanctions"], started_at: "2026-03-04T08:00:00Z", completed_at: "2026-03-04T08:01:10Z", total_duration_seconds: 70 },
    },
    composite_score: 10,
    risk_tier: "CRITICAL",
    recommendation: "Auto-Reject",
    confidence: "HIGH",
    decision: "rejected",
    decided_by: "Jim",
    decided_at: "2026-03-04T08:15:00Z",
    decision_notes: "OFAC sanctioned individual. Automatic rejection. No engagement possible.",
    completed_at: "2026-03-04T08:01:10Z",
    flags: { red: [{ category: "sanctions", title: "OFAC SDN Match", description: "97% match on OFAC Specially Designated Nationals list", source: "OFAC", date: "2026-03-04", severity: "critical" }], yellow: [] },
  },
  {
    id: "5",
    subject_name: "Pacific Trade Alliance",
    subject_type: "organization",
    company_affiliation: null,
    country: "Japan",
    city: "Tokyo",
    brief_bio: "Japanese trade association representing automotive manufacturers seeking US trade policy advocacy.",
    referral_source: "Ambassador Tanaka, former trade envoy",
    engagement_type: "foreign_corporate",
    vetting_level: "standard_vet",
    requested_by: "Jim",
    requested_at: "2026-03-07T08:00:00Z",
    status: "pending",
    pipeline_progress: null,
    result_json: null,
    composite_score: null,
    risk_tier: null,
    recommendation: null,
    confidence: null,
    decision: null,
    decided_by: null,
    decided_at: null,
    decision_notes: null,
    completed_at: null,
    flags: null,
  },
];
